name: Windows Clang vcpkg

on:
  push:
    branches: '*'
    tags: 'v*.*.*'
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    strategy:
      matrix:
        CONFIGURATION: [Debug, Release]
    runs-on: windows-2022
    env:
      CONFIGURATION: ${{ matrix.CONFIGURATION }}
      VCPKG_DEFAULT_TRIPLET: x64-windows
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          choco install ninja &
          vcpkg install zlib qt5-base qt5-tools
          Get-Job | Wait-Job

          #gcm vcpkg (C:\vcpkg)
          #clang --version (C:\Program Files\LLVM\bin, 13.0.0)
      - name: CI-Build
        run: |
          mkdir build
          cd build
          cmake .. `
            -D CMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake `
            -D CMAKE_C_COMPILER=clang `
            -D CMAKE_CXX_COMPILER=clang++ `
            -DCMAKE_BUILD_TYPE=${{ matrix.CONFIGURATION }} `
            -G Ninja
          ninja
      - name: Package artifact
        run: |
          py -3 ci/build.py archive
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: qvgmsplit-${{ matrix.CONFIGURATION }}-v${{ github.run_number }}-dev
          path: archive-root/
      - name: Debug
        shell: cmd
        run: tree /f
      - name: Upload .pdb symbols
        uses: actions/upload-artifact@v2
        with:
          name: qvgmsplit-${{ matrix.CONFIGURATION }}-v${{ github.run_number }}-pdb
          path: build/qvgmsplit.pdb
