name: Windows MinGW64

on:
  push:
    branches: '*'
    tags: 'v*.*.*'
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    strategy:
      matrix:
        CONFIGURATION: [Debug, Release]
    runs-on: windows-2022
    env:
      CONFIGURATION: ${{ matrix.CONFIGURATION }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          # mingw-w64-x86_64-qt5-tools supplies windeployqt
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-qt5-base
            mingw-w64-x86_64-qt5-tools
      - name: CI-Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.CONFIGURATION }} -G Ninja
          ninja
      - name: Package artifact
        run: |
          py -3 ci/build.py archive
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: qvgmsplit-${{ matrix.build }}-v${{ github.run_number }}-dev
          path: archive-root/
      - name: Upload .pdb symbols
        uses: actions/upload-artifact@v2
        with:
          name: qvgmsplit-${{ matrix.build }}-v${{ github.run_number }}-pdb
          path: build/qvgmsplit.pdb
